from_latest_tag = true
ignore_merge_commits = false
disable_changelog = false
generate_mono_repository_global_tag = true
branch_whitelist = [ "main" ]
skip_ci = "[skip ci]"
skip_untracked = false
tag_prefix = "v"

# for global versions only; we don't use global version
pre_bump_hooks = []
post_bump_hooks = []
# for package versions, which is what we actually use
pre_package_bump_hooks = [
    "echo Updating {{package}} to version {{version}}",
    # prepare some source tar/zip for the release we are about to cut
    "rm GITHUB_CHANGELOG.md",
    "tar -czf ../../RELEASE-{{package}}-v{{version}}.tgz ./",
    "zip ../../RELEASE-{{package}}-v{{version}}.zip .",
]
post_package_bump_hooks = [
    "cog changelog --at {{package}}-v{{version}} -t full_hash > GITHUB_CHANGELOG.md",
]

[git_hooks]


[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []


[bump_profiles]

[packages]
auth-keyclock = { path = "plugins/auth-keyclock" }
dashboard-object-viewer = { path = "plugins/dashboard-object-viewer" }
json = { path = "plugins/json" }
matplotlib = { path = "plugins/matplotlib" }
plotly = { path = "plugins/plotly" }
plotly-express = { path = "plugins/plotly-express" }
table-example = { path = "plugins/table-example" }
ui = { path = "plugins/ui" }

